### ISSUE TITLE
MacOS app needs CFBundleIdentifier and CFBundleShortVersionString for MDM

### ISSUE THREAD

**Issue by alastairtech** [netbirdio/netbird#2545]
**Is your feature request related to a problem? Please describe.**
Seems the MacOS app does not have CFBundleIdentifier and CFBundleShortVersionString defined. This makes it harder to deploy using MDM suites as most will call on those strings to check if the app is installed and up to date.

**Describe the solution you'd like**
Add the CFBundleIdentifier and CFBundleShortVersionString values to the automated MacOS app build in the Info.plist file.

**Describe alternatives you've considered**
Tried to add the string values to the app. You can't do this by default when MacOS system integrity protection is enabled. Adding them breaks the app anway.

**Additional context**
NA

**Comment by sc-nanjing** [comment]
I've been trying to deploy the MacOS pkg file via Micrsoft Intune, and when I add the pkg file I get this message below. This seems like it could be related.

The selected app package does not appear to have either a ProductCode or ProductVersion.

**Comment by alastairtech** [comment]
> I've been trying to deploy the MacOS pkg file via Microsoft Intune, and when I add the pkg file I get this message below. This seems like it could be related.
> 
> "The selected app package does not appear to have either a ProductCode or ProductVersion."

I believe this because the mentioned strings are missing. Intune looks for CFBundleIdentifier and CFBundleShortVersionString when uploading pkgs so it can detect the app's status when installed.

**Comment by florian-obradovic** [comment]
Mee too - This affects both amd64 and arm64 versions of the PKG (v0.29.3)
![CleanShot 2024-09-18 at 16 32 19@2x](https://github.com/user-attachments/assets/2880eb52-6763-48eb-9624-f58d3e14597b)

**Comment by florian-obradovic** [comment]
Still the same with 0.30.1 PKGs:
![CleanShot 2024-10-12 at 10 41 16@2x](https://github.com/user-attachments/assets/72c84b5b-43d2-4c2e-9516-b5c2781dca00)

**Comment by mgarces** [comment]
I believe this was fixed from `v0.30.2` release; could you please test it and report back? From that version there is also an universal package (amd64 & arm64).

**Comment by florian-obradovic** [comment]
@mgarces thanks a lot. Confirmed ❤️
![CleanShot 2024-11-04 at 23 40 43@2x](https://github.com/user-attachments/assets/7d33c55b-9b41-4378-8cb8-72214579f3ef)

**Comment by florian-obradovic** [comment]
I think the universal is missing on the "standard download page":
https://github.com/netbirdio/netbird/releases/tag/v0.31.0
![CleanShot 2024-11-04 at 23 43 13@2x](https://github.com/user-attachments/assets/334cbe09-cb17-4806-b404-59e3adf93068)

https://github.com/netbirdio/netbird/releases/tag/v0.31.0

I'm unsure what I need... Do I need both packages?
![CleanShot 2024-11-04 at 23 44 31@2x](https://github.com/user-attachments/assets/79483010-eb35-46be-a8ae-daed7b700611)

**Comment by florian-obradovic** [comment]
**MacOS Menubar icon missing:**
I have a strange issue with netbird on macOS.
Due to the fact that CFBundleIdentifier was missing from the PKGs in the past, I wasn’t able to deploy it using Intune MDM because that attribute is mandatory...

So I deployed it on one client using homeBrew (brew install netbird netbird-ui).

With the new [netbird_0.31.0_darwin.pkg](https://github.com/netbirdio/netbird/releases/download/v0.31.0/netbird_0.31.0_darwin.pkg) available with CFBundleIdentifier populated, I created and deployed an app to my macOS client. (i uninstalled netbird & netbird-ui using brew before).
The installation via Intune MD worked, but I can’t see the Netbird menubar icon. It’s missing but the process is running.
Netbird status -d shows all machines connected, but I can’t launch the UI.

![CleanShot 2024-11-05 at 15 37 17@2x](https://github.com/user-attachments/assets/f991d7a0-14a8-4dfa-aba5-614cc1e6bdfa)

**Comment by mgarces** [comment]
hello @florian-obradovic can you please show us the output of 
```
md5 /Applications/NetBird.app/Contents/MacOS/*
file /Applications/NetBird.app/Contents/MacOS/*
```
I've replicated your setup, but I still get the `netbird-ui` and `netbird` processes running. 
<img width="952" alt="image" src="https://github.com/user-attachments/assets/df0f07a8-f91e-4160-a4d6-974bf6aa58d3">
and
<img width="352" alt="image" src="https://github.com/user-attachments/assets/bc97c0ad-0d3c-421f-96d7-bd8741ab8b5d">

**Comment by mgarces** [comment]
also
```
ps aux | grep -i netbird
```

**Comment by florian-obradovic** [comment]
Hi @mgarces.
Thanks a lot. I'm not sure if I understand what you mean with "but I still get the netbird-ui and netbird processes running."
They're running here as well but not menu bar icon as the one user.

User tinac is no local admin:
```
netbird version
0.31.0

 ps aux |grep -i netbird
root               548   1,0  0,3 411980160  45616   ??  Ss   10:17am   0:10.97 /usr/local/bin/netbird service run --config /etc/netbird/config.json --log-level info --daemon-addr unix:///var/run/netbird.sock --log-file /var/log/netbird/client.log
tinac             1131   0,0  0,3 412813104  52272   ??  S    10:18am   0:01.61 /Applications/NetBird.app/Contents/MacOS/netbird-u
```

```
md5 /Applications/NetBird.app/Contents/MacOS/*
MD5 (/Applications/NetBird.app/Contents/MacOS/netbird) = d0da84253b429d799795da5b27f3331b
MD5 (/Applications/NetBird.app/Contents/MacOS/netbird-ui) = 5ee0f770886b24b3d5732423158f3b52

file /Applications/NetBird.app/Contents/MacOS/*
/Applications/NetBird.app/Contents/MacOS/netbird:    Mach-O 64-bit executable arm64
/Applications/NetBird.app/Contents/MacOS/netbird-ui: Mach-O 64-bit executable arm64
```

Screenshot of Netbird-UI Menu Bar running as localadmin user:
![CleanShot 2024-11-08 at 10 57 31@2x](https://github.com/user-attachments/assets/8ac1f9fd-c074-4beb-96d0-950eb21a5901)

**Comment by leon-th** [comment]
I can confirm that the CFBundleIdentifier and CFBundleShortVersionString are present in newer builds.
Deployment with Intune works flawlessly.
Therefore I believe this feature request/issue can be closed or marked as done.

**Comment by TechHutTV** [comment]
Fixed in PR #2738 (universal bin + sign workflow), shipped in v0.30.2 — the macOS PKG now carries proper `CFBundleIdentifier` and `CFBundleShortVersionString` values, and a universal binary is produced for amd64+arm64. Multiple commenters have since confirmed Intune deployment works. Closing as fixed.
