### ISSUE TITLE
all rosenpass peer failed

### ISSUE THREAD

**Issue by lfarkas** [netbirdio/netbird#2779]
**Describe the problem**

2024-10-24T21:22:03+02:00 ERRO client/internal/rosenpass/manager.go:190: failed to add rosenpass peer: failed to resolve peer endpoint address: lookup 100.76.24.179/32: no such host
time=2024-10-24T21:22:03.375+02:00 level=DEBUG msg="Skipping handshake due to missing endpoint" pid="ajRhlien6HUyn1mrq6BzjAn8jg8oAP3ibK2vnqpxfsg="
time=2024-10-24T21:22:03.379+02:00 level=DEBUG msg="Added peer" pid="ajRhlien6HUyn1mrq6BzjAn8jg8oAP3ibK2vnqpxfsg="
**To Reproduce**

start the service 

**Expected behavior**

run without error

**Are you using NetBird Cloud?**

NetBird Cloud control plane.

**NetBird version**

NetBird client version 0.30.3 on linux/amd64

**Comment by mgarces** [comment]
hello @lfarkas ; can you elaborate on `start the service` part? 
What were the steps you did to start nebird service.

**Comment by lfarkas** [comment]
it's an x86_64 homeassistant addon
```
 Add-on version: v0.30.3
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.2  (amd64 / generic-x86-64)
 Home Assistant Core: 2024.10.3
 Home Assistant Supervisor: 2024.10.3
```
kernel:
```
# uname -a
Linux homeassistant 6.6.54-haos #1 SMP PREEMPT_DYNAMIC Tue Oct 15 12:39:31 UTC 2024 x86_64 HAOS
```
with:
```
netbird up  --foreground-mode --config /config/config.json --log-file console --setup-key XYZ --hostname abc.exmaple.com --enable-rosenpass --rosenpass-permissive --log-level info
```

**Comment by mlsmaycon** [comment]
@lfarkas can you please test using the latest client version if the problem persists, please run the following command:
```shell
netbird debug for 1m --system-info --anonymize
```
Then share the output with us.

**Comment by lfarkas** [comment]
```
[19:39:48] INFO: Rosenpass enabled
[19:39:48] INFO: Rosenpass permissive mode enabled
[19:39:48] INFO: Using info as logging level
[19:39:48] INFO: Starting NetBird Client...
[19:39:48] INFO: netbird up  --foreground-mode --config /config/config.json --log-file console --setup-key XXXXXXXXXXXXXXXXXXXXXXXXXXXXX --hostname homeassistant.lfarkas.org --enable-rosenpass --rosenpass-permissive --log-level info
2024-11-08T19:39:49+01:00 INFO client/internal/connect.go:111: starting NetBird client version 0.31.0 on linux/amd64
2024-11-08T19:39:49+01:00 INFO client/internal/connect.go:240: connecting to the Relay service(s): rels://relay.netbird.io:443
2024-11-08T19:39:49+01:00 INFO relay/client/picker.go:66: try to connecting to relay server: rels://relay.netbird.io:443
2024-11-08T19:39:49+01:00 INFO [relay: rels://relay.netbird.io:443] relay/client/client.go:166: create new relay connection: local peerID: +i/q6dNa3AeF/iNJMH9+CbnsTLmFPfN+/K0KUPJI5wI=, local peer hashedID: sha-Dn9xgXi3A/4FEe90jhVUP/dkvMcxA59y/e7x0g3oZO4=
2024-11-08T19:39:49+01:00 INFO [relay: rels://relay.netbird.io:443] relay/client/client.go:172: connecting to relay server
2024-11-08T19:39:50+01:00 INFO [relay: rels://streamline-de-fra1-2.relay.netbird.io:443] relay/client/client.go:189: relay connection established
2024-11-08T19:39:50+01:00 INFO relay/client/picker.go:84: connected to Relay server: rels://relay.netbird.io:443
2024-11-08T19:39:50+01:00 INFO relay/client/picker.go:58: chosen home Relay server: rels://relay.netbird.io:443
2024-11-08T19:39:50+01:00 INFO client/iface/wgproxy/ebpf/proxy.go:91: local wg proxy listening on: 3128
2024-11-08T19:39:50+01:00 INFO client/iface/wgproxy/factory_kernel.go:29: WireGuard Proxy Factory will produce eBPF proxy
2024-11-08T19:39:50+01:00 INFO client/internal/engine.go:327: rosenpass is enabled
2024-11-08T19:39:50+01:00 INFO client/internal/engine.go:329: running rosenpass in permissive mode
2024-11-08T19:39:52+01:00 INFO client/internal/rosenpass/manager.go:158: starting rosenpass server on port 57047
```
and later:
```
2024-11-08T19:39:53+01:00 ERRO client/internal/rosenpass/manager.go:190: failed to add rosenpass peer: failed to resolve peer endpoint address: lookup 100.76.171.201/32: no such host
2024-11-08T19:39:53+01:00 INFO [peer: 1u25Mrocd2aMv88fUgRnKmM1caynzX+bGTzThCZ3CnE=] client/internal/peer/conn.go:470: start to communicate with peer via relay
2024-11-08T19:39:53+01:00 ERRO client/internal/rosenpass/manager.go:190: failed to add rosenpass peer: failed to resolve peer endpoint address: lookup 100.76.149.154/32: no such host
2024-11-08T19:39:53+01:00 INFO [peer: hCDjKQBW9TBwsZigTRXxvVzpAYE+ZqDHBol4sOSUMl0=] client/internal/peer/conn.go:470: start to communicate with peer via relay
time=2024-11-08T19:39:53.759+01:00 level=DEBUG msg="Skipping handshake due to missing endpoint" pid="Z2/w3OITT9uSosAs718AkjyyvHiHNW64U613Fl607M0="
time=2024-11-08T19:39:53.761+01:00 level=DEBUG msg="Added peer" pid="Z2/w3OITT9uSosAs718AkjyyvHiHNW64U613Fl607M0="
2024-11-08T19:39:54+01:00 INFO [peer: FfiyZKMquYILabBxOquw/jXEuTjhBq6tUvBEPdV3ckY=] client/internal/peer/conn.go:325: set ICE to active connection
2024-11-08T19:39:54+01:00 ERRO client/internal/rosenpass/manager.go:190: failed to add rosenpass peer: failed to resolve peer endpoint address: lookup 100.76.171.201/32: no such host
2024-11-08T19:39:54+01:00 INFO [peer: RtObgAe/KslyFa/t0a/iGwy7HohRzO8xhNNUPIR1ri8=] client/internal/peer/conn.go:325: set ICE to active connection
```

**Comment by mlsmaycon** [comment]
Thanks for sharing the logs. Can you confirm if the issue happens on 0.31.0? We've fixed an issue with slow relay connections in this version.

**Comment by mgarces** [comment]
hello @lfarkas ; we couldn't reproduce your issue on our side, but we will investigate this issue and return to you with more info. 
In the meantime, can you please validate if [0.31.1](https://github.com/netbirdio/netbird/releases/tag/v0.31.1) affects this?

**Comment by lfarkas** [comment]
same error.

**Comment by nazarewk** [comment]
Hello @lfarkas,

We're currently reviewing our open issues and would like to verify if this problem still exists in the [latest NetBird version](https://github.com/netbirdio/netbird/releases).

Could you please confirm if the issue is still there?

We may close this issue temporarily if we don't hear back from you within **2 weeks**, but feel free to reopen it with updated information.

Thanks for your contribution to improving the project!

**Comment by lfarkas** [comment]
this is probably was a rosenpass error, but when it's turn out that rossenpass is still broken i turn it off everywhere and i dare not to turn on since my remote sites become unavailable....
