### ISSUE TITLE
Windows client not connect

### ISSUE THREAD

**Issue by sgm456** [netbirdio/netbird#4526]
The Windows client doesn't connect to the Netbird server on versions 0.58 and 0.58.1.
The latest working version is 0.57.1.

A clear and concise description of what the problem is.

**To Reproduce**

1. Install agent on windows

**Comment by sunstarjeff** [comment]
I came to the Issues page today to see if anyone had reported this issue, after experiencing connectivity issues on several Windows clients.

I'm reverting Windows clients back to 0.57.1 until this issue can be resolved.

**Comment by mlsmaycon** [comment]
@sgm456 @sunstarjeff could you please share the upload key for the following command in recent versions:
```shell
netbird debug bundle --upload-bundle --anonymize
```

**Comment by sunstarjeff** [comment]
Sure, is this what you're needing?

C:\WINDOWS\SystemTemp\netbird.debug.1785713459.zip
Upload file key:
f79e391890ab27fb37c88b3b4be7011e22aa2e5ca6f38ffa9c4481884941f726/fe13d424-65ed-4442-81f7-cbfa604d1254

**Comment by sgm456** [comment]
C:\tmp>netbird debug bundle --upload-bundle --anonymize                                                                 Local file:                                                                                                             C:\WINDOWS\SystemTemp\netbird.debug.1101652429.zip                                                                      Upload file key:                                                                                                        f79e391890ab27fb37c88b3b4be7011e22aa2e5ca6f38ffa9c4481884941f726/42c5f731-21bb-431c-a2fa-21c56434ee88

**Comment by lixmal** [comment]
Can you please run `netbird debug for 1m -UA` instead? Then share the upload file key again.
@sgm456 @sunstarjeff 

Can you also describe what the issue is exactly? "See error" is not helpful

**Comment by mrwsl** [comment]
Our windows clients experience the same on version 0.58.0, while linux clients are not affected. Downgrading the windows clients to 0.57.1 helps. Here is the debug upload bundle:
```
Upload file key:
a43af7f29c88cc80d10dfbf4f3396dd4829a71a3edc2a76a38c81b747a819736/26b072dc-a7cd-4b1c-8fce-6e3a5b5b5a1e
```

EDIT: The "error" is that no device is connected to the client. They are showing `0/x connected`.

**Comment by lixmal** [comment]
Thanks @mrwsl 

For the time being you can downgrade like you did or set this env var:

`netbird service reconfigure --service-env NB_USE_LEGACY_ROUTING=true`

**Comment by sgm456** [comment]
C:\tmp>netbird service reconfigure --service-env NB_USE_LEGACY_ROUTING=true 
Stopping NetBird service...  
Removing existing service configuration... 
Installing service with new configuration...
Starting NetBird service...
NetBird service has been reconfigured and started                                                                                                                                                                                               

C:\tmp>netbird debug for 1m -UA
Error: failed to set log level to TRACE: engine not initialized

C:\tmp>netbird debug for 1m -UA
netbird down
Error: failed to up: up already in progress: current status LoginFailed

After reverting to 0.57.1, I connected successfully.

**Comment by mlsmaycon** [comment]
@sgm456 can you confirm that the issue happens after a few seconds of running the reconfigure command? I mean, if you wait, 10-30 seconds before running `netbird debug for 1m -U -A` does it work?

**Comment by sgm456** [comment]
> [@sgm456](https://github.com/sgm456) can you confirm that the issue happens after a few seconds of running the reconfigure command? I mean, if you wait, 10-30 seconds before running `netbird debug for 1m -U -A` does it work?

After 1 min connected. 0.58.1

**Comment by mlsmaycon** [comment]
@sgm456 thanks for the update. Can you generate the bundle with? 

```shell
netbird debug for 2m -U -A
```

**Comment by davidchi2020** [comment]
I also encountered a very similar issue and noticed a possible pattern: After upgrading the NetBird client on one of my Windows PCs (PC1) from version 0.57.1 to 0.58.0 or 0.58.1, it lost connectivity with some other NetBird peers. These unreachable peers were running either Windows or Linux, and the connectivity issue didn’t seem related to their NetBird client versions. However, I found that if the unreachable peers actively pinged PC1’s NetBird domain name, the connection between them would be restored. Not sure if this observation could provide useful clues for troubleshooting.

**Comment by davidchi2020** [comment]
> I also encountered a very similar issue and noticed a possible pattern: After upgrading the NetBird client on one of my Windows PCs (PC1) from version 0.57.1 to 0.58.0 or 0.58.1, it lost connectivity with some other NetBird peers. These unreachable peers were running either Windows or Linux, and the connectivity issue didn’t seem related to their NetBird client versions. However, I found that if the unreachable peers actively pinged PC1’s NetBird domain name, the connection between them would be restored. Not sure if this observation could provide useful clues for troubleshooting.

On two Windows 10 PCs, after upgrading NetBird from version 0.57.1 to 0.58.1, they were unable to establish a connection. Pinging each other did not help either. It seems the pattern I mentioned earlier was inaccurate—this is quite puzzling.

**Comment by sgm456** [comment]
C:\tmp>netbird debug for 2m -U -A                                                                                       netbird down                                                                                                            netbird up                                                                                                              Remaining time: 00:00:01                                                                                                Duration completed                                                                                                      Creating debug bundle...                                                                                                Local file:                                                                                                             C:\WINDOWS\SystemTemp\netbird.debug.1260464448.zip                                                                      Upload file key:                                                                                                        f79e391890ab27fb37c88b3b4be7011e22aa2e5ca6f38ffa9c4481884941f726/445cb134-ba46-4b9e-82a1-3586402b0df1

**Comment by lixmal** [comment]
It's not clear yet what's wrong, according to the log the correct outbound interface is selected etc

@sgm456 you seem to have  the legacy routing env var enabled
@mrwsl all peers are in `Idle` state so we don't get any valuable info

Please follow these steps and generate another bundle:

1. If activated, deactivate lazy connections. Or if that's not desirable, then ping one of the affected peers while the `netbird debug` runs to activate it
2. Ensure legacy routing is off if previously enabled: `netbird service reconfigure --service-env NB_USE_LEGACY_ROUTING=false`
3. Run netbird client `v0.58.1`
4. If possible, capture traffic on the `wt0` interface via Wireshark or [pktmon](https://learn.microsoft.com/en-us/windows-server/networking/technologies/pktmon/pktmon) before/during the test
5. Run `netbird debug for 2m -AU`
6. Share the upload key, the `pcap` file from the capture and the Windows version with patch level

**Comment by mrwsl** [comment]
```
Upload file key:
a43af7f29c88cc80d10dfbf4f3396dd4829a71a3edc2a76a38c81b747a819736/2a1bd141-29e2-49ac-a486-991a057273a2
```

I pinged a peer while capturing traffic on `wt0` (feel free to delete the Wireshark capture attachment, once you have it).

**Comment by sgm456** [comment]
C:\>netbird service reconfigure --service-env NB_USE_LEGACY_ROUTING=false 
 Stopping NetBird service...  
Removing existing service configuration...  
Installing service with new configuration...  
Starting NetBird service...  
NetBird service has been reconfigured and started                                                                                                                                                                                               

C:\>netbird debug for 2m -AU
Error: failed to set log level to TRACE: engine not initialized                                                                                                                                                                                 

C:\>netbird up
Error: daemon up failed: login backoff cycle failed: rpc error: code = Unknown desc = getting device authorization flow info failed with error: context deadline exceeded

C:\>netbird debug for 2m -AU
Error: failed to up: up already in progress: current status LoginFailed

**Comment by davidchi2020** [comment]
The issue only occurs with versions starting from 0.58.0 up to 0.58.2. I kept pinging a peer in the command line window. After upgrading from 0.57.1 to 0.58.0 (or 0.58.1, 0.58.2), the ping stopped receiving responses. Then, after reinstalling version 0.57.1, the ping started receiving responses again.

**Comment by sgm456** [comment]
0.59, 0.59.1 the problem remains

**Comment by lbios1** [comment]
0.59.2 doesn't work either

**Comment by sgm456** [comment]
0.59.3 doesn't work either too

**Comment by matkoeout** [comment]
I have the same problem with many clients. Since version 58 all clients can´t conntect to peers.

**Comment by davidchi2020** [comment]
After upgrading to version 0.59.4, the issue still persists.

**Comment by davidchi2020** [comment]
<img width="1475" height="438" alt="Image" src="https://github.com/user-attachments/assets/05208b6f-f1e1-4706-86c3-47e57bc2e899" />
The client logs showed that all peers remained Idle, and connections could not be activated by pinging them. The issue was resolved by toggling the "lazy connections" feature off globally in the dashboard. This confirms the problem is a bug in lazy state management, present from version 0.58.0 through to the current 0.59.5.

**Comment by sevensolutions** [comment]
@davidchi2020 can confirm.
As soon as i disable lazy connections in the dashbaord, it starts to work immediately.

**Comment by sgm456** [comment]
After upgrading to version 0.59.5, the issue still persists.

**Comment by zanderson-aim** [comment]
Confirmed as well, disable Lazy Connections Globally and we are good

**Comment by lixmal** [comment]
Hey folks, this should be fixed with https://github.com/netbirdio/netbird/releases/tag/v0.59.7

**Comment by zanderson-aim** [comment]
Looks good here

**Comment by sgm456** [comment]
I figured out the problem.
The problem:
Netbird versions greater than 0.57.1 fail to connect to the server with a "login failed" error.
Cause: Dr.Web Security Space 12 (for workstations)
Disabling all protection components doesn't produce a positive result.
However, if you completely uninstall the antivirus or add Netbird to the exceptions, the connection is established.
The same connection issue occurs with some websites when Dr.Web Security Space is enabled, for example https://pixeldrain.com/ (ERR_SSL_PROTOCOL_ERROR).
It's unclear why the antivirus reacted this way to new versions of Netbird. Something in the TLS/SSL settings in the Netbird client has changed.
It's also unclear why the latest versions of Netbird, when running:
netbird service reconfigure --service-env NB_USE_LEGACY_ROUTING=true, still connect without exceptions in the antivirus.
In general, the cause on the workstation has been determined.

**Comment by Kimmax** [comment]
This is not the problem, login is successful and no "Dr. Web Security" installed.
@lixmal Could you link the commit that fixed this? I'd like to understand what was going on :)

**Comment by lixmal** [comment]
@Kimmax https://github.com/netbirdio/netbird/pull/4646
