### ISSUE TITLE
NetBird 0.60 on macOS menubar shifts on screen (unusual UI/UX behavior) on 16" MBP

### ISSUE THREAD

**Issue by fseesink** [netbirdio/netbird#4819]
**Describe the problem**

This is not so much functional as it is a UI/UX observation.  I just upgraded to NetBird 0.60 on a Mac, and I observed the following:

1. If I click on the menubar icon, I see this:

<img width="181" height="331" alt="Image" src="https://github.com/user-attachments/assets/42f10137-a0f5-4335-afe4-e05161bd0056" />

2. If I then hover my mouse pointer over the up arrow (`^`) at the top of the menu, I then get this:

<img width="190" height="337" alt="Image" src="https://github.com/user-attachments/assets/9700f235-cd69-4afc-8d0d-e31d71e450a1" />

Notice how the menu jumps down on the screen, showing an open gap between the menu bar and menu.

Again, not so much functional as just odd UX.  Thought you should know.

(Also, why is there an up arrow (`^`) at all here?  It would take up no more space to simply show the Connected/Disconnected status in the menu bar.  Just a thought.)

**To Reproduce**

See above.

**Expected behavior**

I expected the menu to stay positioned where it was and reveal whatever was not showing up above the up arrow (`^`).

**Are you using NetBird Cloud?**

Yes I am using NetBird Cloud.

**NetBird version**

NetBird 0.60.0

**Is any other VPN software installed?**

Cisco Secure Client is installed but not running.

**Debug output**

To help us resolve the problem, please attach the following anonymized status output

  netbird status -dA

Not sure this is relevant for this, but sure:
```
$ netbird status -dA
Peers detail:
Events:
  [INFO] SYSTEM (d1e29b90-176a-4851-87f4-ffb87323c060)
    Message: Network map updated
    Time: 9 minutes, 19 seconds ago
  [INFO] SYSTEM (9ae03369-e5cd-40fc-b7eb-92e1c50686d8)
    Message: Network map updated
    Time: 2 minutes, 33 seconds ago
OS: darwin/arm64
Daemon version: 0.60.0
CLI version: 0.60.0
Profile: default
Management: Disconnected
Signal: Disconnected
Relays: 
  [rels://relay.netbird.io:443] is Unavailable, reason: relay connection is not established
Nameservers: 
FQDN: 
NetBird IP: N/A
Interface type: N/A
Quantum resistance: false
Lazy connection: false
SSH Server: Disabled
Networks: -
Forwarding rules: 0
Peers count: 0/0 Connected
```

Create and upload a debug bundle, and share the returned file key:

  netbird debug for 1m -AS -U

*Uploaded files are automatically deleted after 30 days.*

> **NOTE**:  I tried doing this but got the following:
```
$ netbird debug for 1m -AS -U
netbird up
Log level set to trace.
netbird down
netbird up
Remaining time: 00:00:01
Duration completed
Creating debug bundle...
netbird down
Error: failed to restore log level: connect client not initialized
```
> So it is not clear to me whether this was uploaded or not.  And not sure what is meant by "share the returned file key" here.

Alternatively, create the file only and attach it here manually:

  netbird debug for 1m -AS

> **NOTE**:  Got same output as above.

**Screenshots**

See above.

**Additional context**

Again, this is not so much a functional issue, as in something that requires debugging.  This appears to be a UI/UX issue only.

But I thought you should be made aware, as it IS a bit odd in how it presents.  Not sure whether this is avoidable or not.  I believe you are using Fyne.io for the GUI side.  I don't recall it causing this in other apps in the past, but not sure if this is a coding issue, an interaction with the OS issue, or what.

For the record, this is on an M3 MAX 16" MacBook Pro running macOS 26.1.

Interestingly enough, after I wrote the previous line, I checked on my M3 iMac, also running macOS 26.1, and also updated to NetBird 0.60.0 this morning.  And the iMac does NOT exhibit this behavior.  The menu shows as one would expect.

However, I observe that on the iMac (which has a 24" screen) that the menu also does not have the up arrow (`^`), but rather shows the Disconnected status right at the top.  So no need for scrolling up.

Could what I observe on the 16" MBP be due to the fact it has a screen that is not as high?  That is, is there something in the code that determines when to show a scrolling up arrow in the menu vs. simply showing the items?  And is it more about this up arrow triggering this situation than anything else?

**Comment by TimvHerpen** [comment]
It also happens on my 16" M1 Max MBP. On my external 4k screen it behaves like you'd expect, but the 16" display shows the issue mentioned above.
Version 0.60.1 on my part.

**Comment by san983** [comment]
This also happens in 0.60.1 in a MBP 16" M1 pro with Tahoe 26.1

**Comment by acelot** [comment]
MacBook Air 13 M2, MacOS Sequoia 15.7.2, same story

**Comment by t4ov** [comment]
Yep, same for me. MacBook Air M2. 26.1

**Comment by pierrechapuis** [comment]
Same, on M2 MBA, macOS Tahoe 26.1. With the native screen, I get the same UX issue. On a 4K screen, no problem.

**Comment by alexsyw** [comment]
hey, same on mbp m1 pro 14" on macOS Tahoe 26.1 with built-in display at resolution 1800x1169

**Comment by fuad00** [comment]
bump on this

**Comment by brenner-tobias** [comment]
Same for me, 14" M2, MacOS 26.2, 1512 x 982

**Comment by brenner-tobias** [comment]
This is fixed for me in 0.62.1, can anyone confirm?

**Comment by fseesink** [comment]
Sadly no.  I mean it has always looked fine **on my 24" M3 iMac** (here is 0.62.0):

<img width="343" height="331" alt="Image" src="https://github.com/user-attachments/assets/e5574b19-340c-419a-bf55-429a84f870a4" />

But still **on my 16" M3 MBP** I see this, even with latest 0.62.2:

<img width="308" height="342" alt="Image" src="https://github.com/user-attachments/assets/82a2d03e-fa2b-4571-94eb-724aade3cd6c" />

I nearly made the mistake of thinking it was fixed when I read this, as I was sitting on my iMac.  But then I remembered this was on the laptop only that it manifested.  So checked that and, sure enough, it's still there.

The one improvement is that at least it no longer shows the `^` and requires scrolling up.

I strongly suspect this may be a screen resolution thing (specifically height), and that it may well just be something either in macOS itself (I'm on macOS "Tahoe" 26.2) or something in the Fyne library that creates the GUI, where the vertical height on the 24" iMac doesn't trigger this.

It's not like the software doesn't work.  It works just fine.  It is just a strange visual artifact.  And I fully expect that the Fyne library likely has some automatic adjustment to drop-down menus based on the length of the menu vs. the height of the screen, which is why it showed a scroll arrow earlier.  But for whatever reason, it still has this gap.

Again, this is nothing show-stopping. I only reported it to make the devs aware, in case there was something in the code which could account for this.

**Comment by brenner-tobias** [comment]
You are right, I was working on my Dell 4k Screen, the issue still persists when using the MacBook Screen. Sorry for the fals hopes...

**Comment by yusufkandemir** [comment]
I am using https://github.com/jordanbaird/Ice, and the only app I use that doesn't work with it is Netbird UI. Ice says "frame check timed out". I am guessing this is related to this GitHub issue. So, it makes it even more unusable for me. Not sure if that helps further.

**Comment by brenner-tobias** [comment]
Once again: Seems to be fixed, right? At least this time I also check on my MB Retina Display

**Comment by yusufkandemir** [comment]
@brenner-tobias yes, it works fine for me. It works fine with Ice now, too!

---

The only tiny issue is that it starts at the very top like this:

<img width="222" height="278" alt="Image" src="https://github.com/user-attachments/assets/294184b4-db31-461b-bd9b-54ac95920095" />

Then, if you hover over the top arrow, it gets down to where it's supposed to be:

<img width="209" height="303" alt="Image" src="https://github.com/user-attachments/assets/74b4237f-b60e-444e-8b35-e26707399b73" />

This behavior is unlike any other app. Also, unlike any other app, there is a little space between the bottom of the menu bar and the Netbird menu. It is also horizontally a bit more to the right. So, I assume there is a vertical and horizontal offset. I am sharing these details in case it can end up being a separate problem in the future, not because it's a very important issue right now.
